# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f373b1fcb4232f21ff2487a1ac9b0d5fbe883066d82ed7c75a706b1b0d019c46e862a54337404cda7801b58d6f6aa3496bd4cc97c5681c2de4d0788cf6bbe8bf

test:
  secret_key_base: da3d50c9f51c725c80dd90b997ed18cd7018fc6de7a617126573920679464ae98c05d75c7a295e7141cb9e5667b8e0a4ba5d7abb5bf21057fd239eb7a7082f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
